name: FatJar bauen

on:
  push:
    branches: [ "master" ]

jobs:
  job-fatjar:
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        java-version: [17, 21]
        os-version: [ubuntu-latest, windows-latest]
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK ${{ matrix.java-version }} einrichten
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: Maven-Installation checken
      run: ./mvnw --version
    - name: FatJar-Datei mit Maven bauen
      run: ./mvnw --batch-mode clean package
    - name: FatJar-Datei veröffentlichen
      uses: actions/upload-artifact@v3
      with:
        name: KfzKennzeichenRestAPI_FatJar_java${{ matrix.java-version }}_${{ matrix.os-version }}
        path: target/kfzkennzeichen-*.jar
        if-no-files-found: error


